### ISSUE TITLE
Add draggable event

### ISSUE THREAD

**Issue by rhogro** [chan132/draggable_float_widget#2]
Hello, thanks for this awesome widget, really love how easy it is to work, but could you add draggable event for showing the widget? I observed that users have a tendency to drag it from the margin instead of just tapping on it.
Edited because I  had both questions in mind, but one of them answered myself (had a call that was triggering the hide event) and somehow thought about that one while wanting write about the other one.

**Comment by chan132** [comment]
Hey, I'm really sorry for taking so long to get back to you. Unfortunately, I won't be able to support this feature for the time being. I apologize once again for any inconvenience caused! However, feel free to fork the project and customize it according to your own requirements.
